# Generated by Django 4.2.3 on 2023-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_news_created_at_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories", to="news.categories"
            ),
        ),
    ]
