# Generated by Django 4.2.3 on 2023-08-21 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_news_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.users"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(to="news.categories"),
        ),
    ]
